name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/group_9_x2.svg
  - assets/vectors/container_3_x2.svg
  - assets/vectors/group_10_x2.svg
  - assets/vectors/ellipse_1_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/delivery_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/group_4_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/group_7_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/delivery_2_x2.svg
  - assets/vectors/group_5_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/bill_1_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/group_8_x2.svg
  - assets/vectors/group_6_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/outcome_1_x2.svg
  - assets/vectors/delivery_3_x2.svg
  - assets/vectors/delivery_1_x2.svg

